---
## AIY_Voicehat
## GPIO definitions (BCM)
#_GPIO_BUTTON = 23
#_GPIO_LED = 25

- name: "AIY-Voicehat-button"
  signals:
    - gpio_input:
        pins:
          - 23
  neurons:
    - say:
          message:
            - "Hallo, mein Name ist {{kalliope_name}}. Ich warte auf eine Frage von dir."
            - "Hallo, ich heise {{kalliope_name}}. Ich höre jetzt zu."
            - "Hallo, ich bin jetzt bereit."
            - "Du kannst mich jetzt etwas Fragen"
 
    - gpio:
          set_pin_high:
            - 25


