---
  - name: "loxberry-install-finished"
    signals:
      - order: "loxberry-install-finished"
    neurons:
      - say:
          message:
            - "Hallo. Mein Name ist {{kalliope_name}}! Bitte konfiguriere das Plugin und starte den LoxBerry neu."
