  - name: "Repeat-via-api"
    signals:
      - order: "api-repeat-cmd {{ query }}"
    neurons:
      - repeat:
          query: "{{ query }}" 
          say_template:
            - "{{ query }}"

  - name: "Say-hello-to"
    signals:
      - order: "say hi to {{ name }}"
    neurons:
      - repeat:
          name: "{{ name }}"
          say_template:
            - "Hi {{ name }}, and welcome"
