---

  - name: "say-local-date"
    signals:
      - order: "what time is it"
    neurons:
      - systemdate:
          say_template:
            - "it's {{ hours }} and {{ minutes }} minute"

  - name: "say-local-date-from-template"
    signals:
      - order: "which date are we"
    neurons:
      - systemdate:
          file_template: "gloabl_templates/en_systemdate_template.j2"


