---

  - includes:
        - brains/de_say.yml
        - brains/de_systemdate.yml
        - brains/de_neurotransmitter.yml
        - brains/de_uri.yml
        - brains/de_kill_switch.yml        
        - brains/de_repeat.yml
        - brains/de_wikipedia.yml
        - brains/de_loxscontrol_light.yml
        - brains/de_loxscontrol_list.yml
        - brains/de_loxberry_install.yml

  - name: "order-not-found-synapse"
    signals: []
    neurons:
      - say:
          message:
            - "Ich habe nicht verstanden!"
            - "Ich verstehe diesen Befehl nicht."
            - "Bitte wiederhole deine Frage."
            - "Könntest du bitte die Frage wiederholen?"
            - "Ich verstehe das nicht."
            - "Wie bitte?"

  - name: "on-triggered-synapse"
    signals: []
    neurons:
      - say:
          message:
            - "ja bitte?"
            - "Ich höre?"
            - "Ich höre auf Dich?"
            - "Ja?"
            - "Was kann ich für Dich tun?"
            - "Wie kann ich Dir helfen?"

  - name: "on-start-synapse"
    signals: []
    neurons:
      - say:
          message:
            - "Was kann ich für Dich tun?"
