---
# ----------------------------------
# global german brain
#
# Changes may be overriden by plugin update
# make custom changes in usr_brain/usr_brain.yml
#
# Aenderungen hier werden durch ein Plugin-Update überschrieben
# Eigene Anpassungen unter usr_brain/usr_brain.yml vornehmen
#
# ----------------------------------
  - includes: 
        - global_brain/de_systemdate.yml
        - global_brain/de_neurotransmitter.yml
        - global_brain/de_uri.yml
        - global_brain/de_kill_switch.yml        
        - global_brain/de_repeat.yml
        - global_brain/de_wikipedia.yml
        - global_brain/de_loxscontrol_light.yml
        - global_brain/de_loxscontrol_list.yml
        - global_brain/de_loxberry_install.yml
        - global_brain/de_aiy_voicehat.yml
        - usr_brain/usr_brain.yml

  - name: "order-not-found-synapse"
    signals: []
    neurons:
      - say:
          message:
            - "Ich habe nicht verstanden!"
            - "Ich verstehe diesen Befehl nicht."
            - "Bitte wiederhole deine Frage."
            - "Könntest du bitte die Frage wiederholen?"
            - "Ich verstehe das nicht."
            - "Wie bitte?"

  - name: "on-triggered-synapse"
    signals: []
    neurons:
      - say:
          message:
            - "ja bitte?"
            - "Ich höre?"
            - "Ich höre auf Dich?"
            - "Ja?"
            - "Was kann ich für Dich tun?"
            - "Wie kann ich Dir helfen?"

  - name: "on-start-synapse"
    signals: []
    neurons:
      - say:
          message:
            - "Was kann ich für Dich tun?"
