---
# ---------------------------
# Kalliope default settings
# Use YAML syntax
# ---------------------------

# ---------------------------
# Trigger
# ---------------------------
# This is the trigger that will catch your magic work to wake up Kalliope
default_trigger: "snowboy"

# Trigger engine configuration
# Available engine are:
# - snowboy
triggers:
  - snowboy:
      pmdl_file: "REPLACEINSTALLFOLDER/data/plugins/REPLACEFOLDERNAME/trigger/kalliope-DE-samples.pmdl"


# ---------------------------
# Speech to text
# ---------------------------

# This is the STT that will be used by default
default_speech_to_text: "google"

# Spreech to Text engines configuration
# Available engine are:
# - google (via SpeechRecognition)
# - wit
# - bing
# - apiai
# - houndify
# - cmusphinx (must be installed first)
speech_to_text:
  - google:
      language: "de-DE"
  - wit:
      key: "place your key here"
  - bing: # API not working : credential fails ..
      key: "place your key here"
  - apiai:
      key: "place your key here"
      language: "de"
  - houndify:
      key: "place your key here"
      client_id: "place your key here"
  #- cmusphinx

# ---------------------------
# Text to speech
# ---------------------------
# This is the default TTS that will be used by Kalliope to talk.
default_text_to_speech: "pico2wave"
# where we store generated audio files from TTS engine to reuse them
cache_path: "/tmp/kalliope_tts_cache"

# Text to Spreech engines configuration
# Available engine are:
# - pico2wave
# - watson
# - googletts
# - voicerss
text_to_speech:
  - pico2wave:
      language: "de-DE"
      cache: True
  - googletts:
      language: "de"
      cache: True
      convert_to_wav: True
  - voicerss:
      language: "de-DE"
      cache: True

# ---------------------------
# players
# ---------------------------
# This is the sound player that will be used by default
default_player: "pyaudioplayer"

# players configuration
# Available engine are:
# - mplayer
# - pyalsaaudio       # no mp3
# - pyaudioplayer     # no mp3
# - sounddeviceplayer # no mp3
players:
  - mplayer: {}
  - pyalsaaudio:
#     device: "plughw:CARD=ALSA,DEV=0"
     convert_to_wav: False
  - pyaudioplayer:
     convert_to_wav: True
  - sounddeviceplayer:
     convert_to_wav: True

# ---------------------------
# Hooks
# ---------------------------
hooks:
  on_start: "on-start-synapse"
  on_waiting_for_trigger:
  on_triggered: "on-triggered-synapse"
  on_start_listening:
  on_stop_listening:
  on_order_found:
  on_order_not_found: "order-not-found-synapse"
  on_mute:
  on_unmute:
  on_start_speaking:
  on_stop_speaking:

# ---------------------------
# Rest API
# ---------------------------
rest_api:
  active: True
  port: 5000
  password_protected: True
  login: admin
  password: secret

# ---------------------------
# resource directory path
# ---------------------------
resource_directory:
  neuron: "REPLACEINSTALLFOLDER/data/plugins/REPLACEFOLDERNAME/neurons"
  stt: "REPLACEINSTALLFOLDER/data/plugins/REPLACEFOLDERNAME/stt"
  tts: "REPLACEINSTALLFOLDER/data/plugins/REPLACEFOLDERNAME/tts"

# ---------------------------
# Global files variables
# /!\ If a variable is defined in different files, the last file defines the value.
# ---------------------------
var_files:
  - REPLACEINSTALLFOLDER/config/plugins/REPLACEFOLDERNAME/vr_loxscontrol.yml

# -------------
# Start options
# -------------
#start_options:
#  muted: False

