---
# ----------------------------------
# global english brain
#
# Changes may be overriden by plugin update
# make custom changes in usr_brain/usr_brain.yml
# ----------------------------------
  - includes:
        - global_brain/en_systemdate.yml
        - global_brain/en_neurotransmitter.yml
        - global_brain/en_uri.yml
        - global_brain/en_repeat.yml
        - global_brain/en_loxberry_install.yml
        - usr_brain/usr_brain.yml

  - name: "order-not-found-synapse"
    signals: []
    neurons:
      - say:
          message:
            - "I haven't understood"
            - "I don't know this order"
            - "Please renew your order"
            - "Would you please reword your order"
            - "Can ou please reformulate your order"
            - "I don't recognize that order"

  - name: "on-triggered-synapse"
    signals: []
    neurons:
      - say:
          message:
            - "yes sir?"
            - "I'm listening"
            - "I'm listening to you"
            - "sir?"
            - "what can i do for you?"
            - "Speaking"
            - "how can i help you?"

  - name: "on-start-synapse"
    signals: []
    neurons:
      - say:
          message: "I'm ready"


