---

  - includes:
        - brains/fr_say.yml
        - brains/fr_systemdate.yml
        - brains/fr_neurotransmitter.yml

  - name: "default-synapse"
    signals:
      - order: "default-synapse"
    neurons:
      - say:
          message:
            - "Je n'ai pas compris vôtre ordre"
            - "Je ne connais pas cet ordre"
            - "Veuillez renouveller votre ordre"
            - "Veuillez reformuller s'il vous plait"
            - "Je n'ai pas saisi cet ordre"


