---
- name: "turn-on-room"
  signals:
    - order: "schalte das licht im {{control_room}} an"
    - order: "schalte das licht in der {{control_room}} an"    
#    - order: "Licht im {{control_room}} an"
#    - order: "Licht in der {{control_room}} an"    
#    - order: "Licht an im {{control_room}}"
#    - order: "Licht an in der {{control_room}}"     
  neurons:
    - loxscontrol:
        lx_ip: "{{lx_ip}}"
        lx_user: "{{lx_user}}"
        lx_password: "{{lx_password}}"
        control_room: "{{control_room}}"
        newstate: "on"
        control_type: lights
        action: "change"        
        file_template:  "templates/de_loxscontrol_template.j2"

- name: "turn-off-room"
  signals:
    - order: "schalte das licht im {{control_room}} aus"
    - order: "schalte das licht in der {{control_room}} aus"    
#    - order: "licht im {{control_room}} aus"
#    - order: "licht in der {{control_room}} aus"    
#    - order: "licht aus im {{control_room}}"
#    - order: "licht aus in der {{control_room}}"     
  neurons:
    - loxscontrol:
        lx_ip: "{{lx_ip}}"
        lx_user: "{{lx_user}}"
        lx_password: "{{lx_password}}"
        control_room: "{{control_room}}"
        newstate: "off"
        control_type: lights
        action: "change"
        file_template:  "templates/de_loxscontrol_template.j2"         
          
- name: "turn-on-named"
  signals:
    - order: "schalte das {{control_name}} an"
    - order: "schalte {{control_name}} an"    
  neurons:
    - loxscontrol:
        lx_ip: "{{lx_ip}}"
        lx_user: "{{lx_user}}"
        lx_password: "{{lx_password}}"
        control_name: "{{control_name}}" 
        newstate: "on"  
        action: "change"  
        file_template:  "templates/de_loxscontrol_template.j2"

- name: "turn-off-named"
  signals:
    - order: "schalte das {{control_name}} aus"
    - order: "schalte {{control_name}} aus"      
  neurons:
    - loxscontrol:
        lx_ip: "{{lx_ip}}"
        lx_user: "{{lx_user}}"
        lx_password: "{{lx_password}}"
        control_name: "{{control_name}}" 
        newstate: "off"
        action: "change"         
        file_template:  "templates/de_loxscontrol_template.j2"

- name: "turn-on-light"
  signals:
    - order: "schalte das Licht ein"
    - order: "schalte das Licht an"    
    - order: "Licht ein"
    - order: "Licht an"
  neurons:
    - say:
            message: "In welchem Raum soll ich das Licht einschalten?"
    - neurotransmitter:
          from_answer_link:
            - synapse: "turn-on-room"
              answers:
                - "im Raum {{control_room}}"
                - "im {{control_room}}"
                - "in der {{control_room}}"                  
            - synapse: "default-ok"
              answers:
                - "überhaupt nicht"
                - "vergiss es"
                - "hat sich erledigt"
          default: "default-synapse"

- name: "turn-off-light"
  signals:
    - order: "schalte das Licht aus"
    - order: "Licht aus"    
  neurons:
    - say:
            message: "In welchem Raum soll ich das Licht ausschalten?"
    - neurotransmitter:
          from_answer_link:
            - synapse: "turn-off-room"
              answers:
                - "im Raum {{control_room}}"
                - "im {{control_room}}"
                - "in der {{control_room}}"                 
            - synapse: "default-ok"
              answers:
                - "überhaupt nicht"
                - "vergiss es"
                - "hat sich erledigt"
          default: "default-synapse"


