  - name: "Repeat-via-api"
    signals:
      - order: "api-repeat-cmd {{ query }}"
    neurons:
      - repeat:
          args:
            - query
          say_template:
            - "{{ query }}"

  - name: "Say-hello-to"
    signals:
      - order: "sage hallo zu {{ name }}"
    neurons:
      - repeat:
          args:
            - name
          say_template:
            - "Hallo {{ name }}, und willkommen"
