---
  - name: "horoscope-scorpio"
    signals:
      - order: "Wie ist mein Horoskop heute"
    neurons:
      - say:
          message: "Scorpio Horoskop von heute"
      - uri:
          url: "http://theastrologer-api.herokuapp.com/api/horoscope/scorpio/today"
          method: GET
          say_template:
              - "{{ content.horoscope }}"
